FROM node:18-alpine3.16

RUN apk add --no-cache postgresql-client
RUN apk add --no-cache bash

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY product_api ./product_api/

COPY tsconfig.json ./

COPY . .

# Generate prisma client
RUN npx prisma generate --schema=product_api/prisma_product/schema.prisma

EXPOSE 4001

# defined command to execute app
CMD ["bash", "entrypoint_product.sh"]
