FROM node:18-alpine

WORKDIR /app

COPY package.json .

## Initialise prisma
RUN npx prisma init --datasource-provider postgresql

### Migrate the schema
RUN npx prisma migrate dev --name init

RUN yarn install

COPY . .

EXPOSE 8081

CMD [ "yarn", "run", "preview" ]
FROM node:18-alpine

WORKDIR /app

COPY package*.json .

COPY prisma ./prisma/

COPY .env ./

COPY tsconfig.json ./

COPY . .

RUN npm install

RUN npx prisma generate

### Migrate the schema
EXPOSE 8080

CMD [ "yarn", "dev" ]
