FROM node:alpine

WORKDIR /app

COPY package*.json ./

COPY prisma ./prisma/

COPY .env ./

COPY tsconfig.json ./

COPY . .

RUN npm install

RUN npx prisma generate

## Initialise prisma
# RUN npx prisma init --datasource-provider postgresql

### Migrate the schema
# RUN npx prisma migrate dev --name init

EXPOSE 4001

CMD [ "yarn", "dev" ]

