FROM node:18-alpine

RUN apk add --no-cache postgresql-client
RUN apk add --no-cache bash

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY prisma_product ./prisma_product/

COPY ../.env .

COPY tsconfig.json ./

COPY . .

# Generate prisma client
RUN npx prisma generate

EXPOSE 4001

# defined command to execute app
CMD ["bash", "entrypoint_product.sh"]
