FROM node:18-alpine

RUN apk add --no-cache postgresql-client
RUN apk add --no-cache bash

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY prisma_bank ./prisma_bank/

COPY .env ./

COPY tsconfig.json ./

COPY . .

# Generate prisma client
RUN npx prisma generate --schema=prisma_bank/schema.prisma

EXPOSE 4002

# defined command to execute app
CMD ["bash", "entrypoint_bank.sh"]
