FROM node:18-alpine

RUN apk add --no-cache postgresql-client
RUN apk add --no-cache bash

WORKDIR /app

COPY bank_api/package*.json ./

RUN npm install

COPY . .

# Generate prisma client
RUN npx prisma generate --schema=./bank_api/prisma_bank/schema.prisma

RUN chmod +x ./bank_api/entrypoint_bank.sh

EXPOSE 4002

# defined command to execute app
CMD ["sh", "./bank_api/entrypoint_bank.sh"]

